export const MASTER_BINDERS = {
  pokemon: {
    label: 'Pokémon',
    icon: '⚡',
    sets: [
      'Base Set', 'Jungle', 'Fossil', 'Base Set 2', 'Team Rocket',
      'Gym Heroes', 'Gym Challenge',
      'Neo Genesis', 'Neo Discovery', 'Neo Revelation', 'Neo Destiny',
      'Expedition', 'Aquapolis', 'Skyridge',
      'EX Ruby & Sapphire', 'EX Sandstorm', 'EX Dragon', 'EX Team Magma vs Team Aqua',
      'EX Hidden Legends', 'EX FireRed & LeafGreen', 'EX Team Rocket Returns',
      'EX Deoxys', 'EX Emerald', 'EX Unseen Forces', 'EX Delta Species',
      'EX Legend Maker', 'EX Holon Phantoms', 'EX Crystal Guardians',
      'EX Dragon Frontiers', 'EX Power Keepers',
      'Diamond & Pearl', 'Mysterious Treasures', 'Secret Wonders', 'Great Encounters',
      'Majestic Dawn', 'Legends Awakened', 'Stormfront',
      'Platinum', 'Rising Rivals', 'Supreme Victors', 'Arceus',
      'HeartGold SoulSilver', 'Undaunted', 'Triumphant', 'Call of Legends',
      'Black & White', 'Emerging Powers', 'Noble Victories', 'Next Destinies',
      'Dark Explorers', 'Dragons Exalted', 'Boundaries Crossed',
      'Plasma Storm', 'Plasma Freeze', 'Plasma Blast', 'Legendary Treasures',
      'XY', 'Flashfire', 'Furious Fists', 'Phantom Forces', 'Primal Clash',
      'Roaring Skies', 'Ancient Origins', 'BREAKthrough', 'BREAKpoint',
      'Generations', 'Fates Collide', 'Steam Siege', 'Evolutions',
      'Sun & Moon', 'Guardians Rising', 'Burning Shadows', 'Crimson Invasion',
      'Ultra Prism', 'Forbidden Light', 'Celestial Storm', 'Cosmic Eclipse',
      'Team Up', 'Unbroken Bonds', 'Unified Minds', 'Hidden Fates',
      'Shining Legends', 'Dragon Majesty', 'Lost Thunder',
      'Sword & Shield', 'Rebel Clash', 'Darkness Ablaze', "Champion's Path",
      'Vivid Voltage', 'Shining Fates', 'Battle Styles', 'Chilling Reign',
      'Evolving Skies', 'Celebrations', 'Fusion Strike',
      'Brilliant Stars', 'Astral Radiance', 'Pokemon GO', 'Lost Origin',
      'Crown Zenith', 'Scarlet & Violet', 'Paldea Evolved', 'Obsidian Flames',
      'Paldean Fates', 'Temporal Forces', 'Twilight Masquerade', 'Shrouded Fable',
      'Stellar Crown', 'Surging Sparks', 'Prismatic Evolutions', 'Journey Together',
      'Destined Rivals', 'Black Bolt', 'White Flare', 'Mega Evolution',
    ],
  },
  magic: {
    label: 'Magic',
    icon: '🔮',
    sets: [
      'Foundations', 'Modern Horizons', 'Modern Horizons 2', 'Modern Horizons 3',
      'Bloomburrow', 'Duskmourn', 'The Lost Caverns of Ixalan', 'Wilds of Eldraine',
      'March of the Machine', 'Phyrexia: All Will Be One', "The Brothers' War",
      'Dominaria United', 'Streets of New Capenna', 'Kamigawa: Neon Dynasty',
      'Innistrad: Crimson Vow', 'Innistrad: Midnight Hunt',
      'Adventures in the Forgotten Realms', 'Strixhaven: School of Mages',
      'Kaldheim', 'Zendikar Rising', 'Core Set 2021', 'Ikoria: Lair of Behemoths',
      'Theros Beyond Death', 'Throne of Eldraine', 'Core Set 2020',
      'War of the Spark', 'Ravnica Allegiance', "Guilds of Ravnica",
      'Core Set 2019', 'Dominaria', 'Rivals of Ixalan', 'Ixalan',
      'Hour of Devastation', 'Amonkhet', 'Aether Revolt', 'Kaladesh',
      'Eldritch Moon', 'Shadows Over Innistrad', 'Oath of the Gatewatch',
      'Battle for Zendikar', 'Magic Origins', 'Dragons of Tarkir',
    ],
  },
  lorcana: {
    label: 'Lorcana',
    icon: '✨',
    sets: [
      'The First Chapter', 'Rise of the Floodborn', 'Into the Inklands',
      "Ursula's Return", 'Shimmering Skies', 'Azurite Sea',
    ],
  },
  sports: {
    label: 'Sports Cards',
    icon: '⚾',
    sets: [
      '1989 Upper Deck Baseball', '1986 Fleer Basketball', '2000 Bowman Chrome Football',
      '1952 Topps Baseball', '1984 Topps Football', '1993 Upper Deck SP Football',
      '1998 Topps Chrome Basketball', '2003 Topps Chrome Football',
      '2011 Topps Chrome Football', '2017 Panini Prizm Basketball',
      '2020 Panini Prizm Football', '2019 Panini National Treasures Football',
      '1985 Topps Baseball', '1991 Upper Deck Baseball',
      '2001 Topps Baseball', '1994 Upper Deck Baseball',
    ],
  },
  funko: {
    label: 'Funko',
    icon: '🎭',
    sets: [
      'Marvel', 'Disney', 'Star Wars', 'Harry Potter', 'Anime',
      'DC Comics', 'NBA', 'NFL', 'Stranger Things', 'Game of Thrones',
      'The Walking Dead', 'Naruto', 'Dragon Ball', 'One Piece',
      'Pokemon', 'SpongeBob', 'Horror', 'Animation',
    ],
  },
  coins: {
    label: 'Coins',
    icon: '🪙',
    sets: [
      'State Quarters', 'Morgan Dollars', 'American Silver Eagles',
      'Peace Dollars', 'Lincoln Cents', 'Jefferson Nickels',
      'Roosevelt Dimes', 'Washington Quarters', 'Franklin Half Dollars',
      'Kennedy Half Dollars', 'Barber Half Dollars', 'Walking Liberty Half Dollars',
      'Buffalo Nickels', 'Mercury Dimes', 'Barber Dimes',
      'Indian Head Cents', 'Two Cent Pieces', 'Three Cent Pieces',
    ],
  },
  memorabilia: {
    label: 'Sports Memorabilia',
    icon: '🏆',
    sets: [
      'Super Bowl Programs', 'Signed Baseball Collection', 'Signed Football Collection',
      'Signed Basketball Collection', 'World Series Programs', 'Olympic Memorabilia',
      'Championship Rings', 'Hall of Fame Induction Items',
    ],
  },
};